/**
 * orval-wrap Demo
 * Full-featured demonstration of type-safe API client generation with orval
 *
 * Run: pnpm generate (after configuring orval.config.ts)
 *
 * This demo showcases:
 * 1. Generated type definitions from OpenAPI schema
 * 2. React Query hooks usage
 * 3. Axios client with custom instance
 * 4. Zod schema validation (auto-generated)
 * 5. Effect-TS integration
 */

// ============================================================
// SECTION 1: Type Definitions (auto-generated by orval)
// ============================================================
// These types are auto-generated from your OpenAPI spec.
// Do NOT edit manually — regenerate after updating the schema.

// --- OpenAPI Schema Example: Pet Store ---
/*
openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
paths:
  /pets/{petId}:
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
          enum: [available, pending, sold]
*/

// ============================================================
// SECTION 2: Generated Client Usage (React Query)
// ============================================================

// --- After running `orval --config orval.config.ts`, you get: ---
// import { getPetById, createPet, listPets, updatePet, deletePet } from '../gen/api';
// import { useQuery, useMutation } from '@tanstack/react-query';

/**
 * Example: Fetch a pet by ID using React Query hook
 * The hook is auto-generated based on your OpenAPI schema
 */
// function useGetPet(petId: string) {
//   return useQuery({
//     queryKey: ['pet', petId],
//     queryFn: () => getPetById({ petId }),
//   });
// }

/**
 * Example: Create a new pet
 */
// function useCreatePet() {
//   return useMutation({
//     mutationFn: (newPet: CreatePet) => createPet(newPet),
//     onSuccess: () => console.log('Pet created!'),
//   });
// }

// ============================================================
// SECTION 3: Custom Axios Client
// ============================================================

// import axios from 'axios';
// import { getPetById, createPet } from '../gen/api';

/**
 * Custom Axios instance with interceptors and base URL
 */
// const apiClient = axios.create({
//   baseURL: 'https://petstore.swagger.io/v2',
//   timeout: 10000,
//   headers: { 'Content-Type': 'application/json' },
// });

// apiClient.interceptors.response.use(
//   (response) => response,
//   (error) => {
//     console.error('API Error:', error.message);
//     return Promise.reject(error);
//   }
// );

/**
 * Fetch pet using custom Axios client
 */
// async function fetchPetWithClient(petId: string) {
//   const response = await getPetById({ petId }, { axios: apiClient });
//   return response.data;
// }

// ============================================================
// SECTION 4: Zod Validation (auto-generated schemas)
// ============================================================

// import { z } from 'zod';

// Auto-generated Zod schemas from OpenAPI spec
// These validate your API responses at runtime

// const PetSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   status: z.enum(['available', 'pending', 'sold']).optional(),
// });

// const CreatePetSchema = z.object({
//   name: z.string().min(1),
//   status: z.enum(['available', 'pending', 'sold']).optional(),
// });

/**
 * Runtime validation example
 */
// function validatePet(data: unknown): Pet {
//   const result = PetSchema.safeParse(data);
//   if (!result.success) {
//     throw new Error(`Invalid pet data: ${result.error.message}`);
//   }
//   return result.data;
// }

// const apiResponse = { id: 1, name: 'Buddy', status: 'available' };
// const pet = validatePet(apiResponse);
// console.log('Validated pet:', pet);

// ============================================================
// SECTION 5: Solid Query / Vue Query / Svelte Query
// ============================================================

// --- Solid Query ---
// import { createQuery, createMutation } from '@tanstack/solid-query';
// import { getPetById, createPet } from '../gen/solid-api';

// function useGetPet(petId: string) {
//   return createQuery(() => ({
//     queryKey: ['pet', petId],
//     queryFn: () => getPetById({ petId }),
//   }));
// }

// --- Vue Query ---
// import { useQuery, useMutation } from '@tanstack/vue-query';
// import { getPetById, createPet } from '../gen/vue-api';

// function useGetPet(petId: string) {
//   return useQuery({ queryKey: ['pet', petId], queryFn: () => getPetById({ petId }) });
// }

// --- Svelte Query ---
// import { createQuery, createMutation } from '@tanstack/svelte-query';
// import { getPetById, createPet } from '../gen/svelte-api';

// function useGetPet(petId: string) {
//   return createQuery({ queryKey: ['pet', petId], queryFn: () => getPetById({ petId }) });
// }

// ============================================================
// SECTION 6: Hono + fetch client
// ============================================================

// import { Hono } from 'hono';
// import { getPetById, createPet } from '../gen/hono-api';

// const app = new Hono();

// app.get('/pets/:petId', async (c) => {
//   const petId = c.req.param('petId');
//   const response = await getPetById({ petId });
//   return c.json(response.data);
// });

// ============================================================
// SECTION 7: Angular HTTP Client
// ============================================================

// import { HttpClient } from '@angular/common/http';
// import { getPetById, createPet } from '../gen/angular-api';

// constructor(private http: HttpClient) {}

// getPet(petId: string) {
//   return this.http.get<Pet>(`/pets/${petId}`);
// }

// ============================================================
// SECTION 8: Next.js App Router (Server Component)
// ============================================================

// import { getPetById } from '../gen/fetch-api';

// async function PetPage({ params }: { params: { petId: string } }) {
//   const response = await getPetById({ petId: params.petId });
//   const pet = response.data;
//   return <div>{pet.name}</div>;
// }

// ============================================================
// SECTION 9: Effect-TS integration
// ============================================================

// import { Effect } from 'effect';
// import { getPetById } from '../gen/effect-api';

// const program = Effect.flatMap(
//   getPetById({ petId: '1' }),
//   (response) => Effect.succeed(response.data)
// );

// Effect.runPromise(program).then(console.log).catch(console.error);

// ============================================================
// SECTION 10: MCP Server (Model Context Protocol)
// ============================================================

// import { McpServer } from '@modelcontextprotocol/sdk/server';
// import { getPetById, createPet } from '../gen/mcp-api';

// const server = new McpServer({ name: 'pet-store', version: '1.0.0' });

// server.tool('getPet', { petId: 'string' }, async ({ petId }) => {
//   const response = await getPetById({ petId });
//   return { content: [{ type: 'text', text: JSON.stringify(response.data) }] };
// });

// ============================================================
// SECTION 11: Error Handling Pattern
// ============================================================

// import { getPetById } from '../gen/api';

/**
 * Standard error handling with try/catch
 */
// async function safeGetPet(petId: string) {
//   try {
//     const response = await getPetById({ petId });
//     return { success: true as const, data: response.data };
//   } catch (error: unknown) {
//     if (axios.isAxiosError(error)) {
//       return { success: false as const, error: error.message };
//     }
//     return { success: false as const, error: 'Unknown error' };
//   }
// }

// ============================================================
// SECTION 12: Batch Requests
// ============================================================

// import { getPetById } from '../gen/api';

/**
 * Parallel fetching of multiple pets
 */
// async function fetchMultiplePets(petIds: string[]) {
//   const responses = await Promise.all(
//     petIds.map((id) => getPetById({ petId: id }))
//   );
//   return responses.map((r) => r.data);
// }

// const pets = await fetchMultiplePets(['1', '2', '3']);
// console.log('Fetched pets:', pets);
